# Generated by Django 4.1.1 on 2022-09-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_description_product_minidescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='miniDescription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
